language: node_js
node_js:
  - "8"
  - "10"
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - npm i
  - sleep 2
script:
  - npm test
  - npm build
#deploy:
#  provider: heroku
#  api_key: ...
#  app: my-app-123
#  on: production

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
